apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-hao
  annotations:
    "store.halo.run/app-id": "app-MgZJX"
spec:
  displayName: Hao
  author:
    name: veyvin
    website: https://github.com/veyvin
  customTemplates:
    page:
      - name: 热门文章页面模版
        description: 按访问量排行展示热门文章
        screenshot:
        file: hot.html

  description: Halo 2.x Theme base on Thymeleaf, Referring to Butterfly and Heo
  logo: /themes/theme-hao/assets/images/hao-logo.jpg
  homepage: https://www.halo.run/store/apps/app-MgZJX
  issues: https://github.com/veyvin/halo-theme-hao/issues
  repo: https://github.com/veyvin/halo-theme-hao
  settingName: "theme-hao-setting"
  configMapName: "theme-hao-configMap"
  version: "1.9.11"
  requires: ">=2.22.8"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/chengzhongxue/halo-theme-hao/blob/main/LICENSE"
